feature/TM-37
EduardsZv/task_manager pull request #5
Opened 2024-08-15 12:43 UTC by EduardsZv

Created registration page

2024-08-15 12:55 UTC, wanpii requested changes

2024-08-15 12:55 UTC, wanpii commented on taskManagerApp/src/app/login-page/login-page.component.scss
> +    cursor:pointer;
formatting

2024-08-15 12:55 UTC, wanpii commented on taskManagerApp/src/app/registration-page/registration-page.component.scss
> +    cursor:pointer;
formatting

2024-08-15 12:55 UTC, wanpii commented on taskManagerApp/src/app/shared/services/users.service.ts
> +        this.showNavbarSubject.next(true);
what's this showNavbarSubject for by the way? I forgot to ask in the previous PR

2024-08-16 10:24 UTC, EduardsZv commented on taskManagerApp/src/app/shared/services/users.service.ts
> +        this.showNavbarSubject.next(true);
showNavbarSubject acts as a boolean variable, so that the navbar can appear and disappear, depending on whether the user is logged in or not. I needed a variable that can dynamically change so that the page would respond to the changes. In app.component.html there is a *ngIf="showNavbar$" that decides if the navbar is shown. Maybe there is a better and easier way to do this, but this was my first idea that worked.

2024-08-16 10:28 UTC, wanpii commented on taskManagerApp/src/app/shared/services/users.service.ts
> +        this.showNavbarSubject.next(true);
You could use loggedInUser for that, no? Would not need a separate variable for this, since you're looking for a logged in user, if a user is not logged in then loggedInUser would be null, but this approach also works, less code if you use loggedInUser

2024-08-16 10:28 UTC, wanpii approved these changes

2024-08-16 10:29 UTC, merged